name: kubescape-scan

on:
  push:

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: avinashupadhya99/kubescape-action@main
        with:
          args: "--verbose"
          files: "kubernetes-prod/*.yaml"
          framework: |
            'nsa','devopsbest'
          # control: "Configured liveness probe"
      - name: Archive kubescape scan results
        uses: actions/upload-artifact@v2
        with:
          name: kubescape-scan-report
          path: results.xml

