name: kubescape-scan

on:
  push:

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: avinashupadhya99/kubescape-action@main
        with:
          args: "--format junit --output results.xml"
          files: "kubernetes-prod/*.yaml"
          framework: 
          - "nsa"
          - "devopsbest"
          # control: "Configured liveness probe" 

